### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by xzima** [xzima/gradle-semantic-release-example#4]
## Что нужно сделать?

- [x] создан проект gradle+kotlin
- [x] добавил проверку commitLint для github actions и git hooks
- [x] `[amazing-github-template]` добавил синхронизацию labels и их проверку в pull requests
- [ ] `[amazing-github-template]` создан репозиторий на github с лицензией и readme
- [ ] добавить механизм обновления зависимостей через renovate
- [X] `[task management][amazing-github-template]` добавить шаблоны issues
- [X] `[task management]` добавить механизм создания pull requests на основе issues
- [ ] добавить автоматическое создание pull request для gitflow
- [ ] `[semantic-release]` добавить механизм обновления версии в gradle.properties
- [ ] `[semantic-release]` добавить генерацию CHANGELOG.md
- [ ] `[semantic-release]` организовать процесс выкатки релиза, чтобы его можно было
  частично-перезапускать([idea](https://github.com/semantic-release/semantic-release/discussions/2331))
- [ ] `[semantic-release]` добавить публикацию в docker hub
- [ ] `[semantic-release]` добавить нотификации об удачном/сломанном релизе
- [ ] `[test]` добавить unit-tests и их вызов в CI
- [ ] `[test]` добавить линтеры([idea](https://github.com/diffplug/spotless))
- [ ] `[license][test]` добавить проверку лицензионных заголовков
- [ ] `[license][gradle]` добавить функцию автоматического задания лицензионных заголовков
- [ ] `[license][semantic-release]` добавить генерацию LICENSES_THIRD_PARTY.txt
- [ ] `[gradle]` вынести зависимости в toml
- [ ] `[gradle]` добавлять покрытие тестами jacoco
- [ ] `[gradle]` добавлять аналогию maven-enforcer-plugin
- [ ] `[gradle]` проверять конфликты зависимостей
- [ ] добавить docker-compose для локальных запусков

**Comment by xzima** [comment]
вместо maven-enforcer-plugin:
- используется gradle toolchain для контроля версии jdk(без vendor)
- используется gradlew для контроля версии gradle

необходимо добавить проверку конфликтов версий зависимостей

**Comment by xzima** [comment]
[semantic-release] организовать процесс выкатки релиза, чтобы его можно было
частично-перезапускать(https://github.com/semantic-release/semantic-release/discussions/2331):
- реализовано посредством вынесения публикации артифакта из процессов semantic-release
- теперь semantic-release job выполняет только публикацию релиза
- далее по хуку публикации релиза вызывается job, в котором и происходит публикации артифакта

**Comment by xzima** [comment]
[license][semantic-release] добавить генерацию LICENSES_THIRD_PARTY.txt:
- наличие файла LICENSES_THIRD_PARTY.txt избыточно, так как с точки зрения исходников информация есть в Dependency graph github-а
- а для артифактов поставка данной информации описанна в [readme](https://github.com/xzima/gradle-semantic-release-example?tab=readme-ov-file#%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BB%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D0%B8-%D0%B2-jar-%D0%B0%D1%80%D1%82%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%B5)
